In [53]:
import numpy as np
from scipy import linalg

In [105]:
teamFx = np.array([1,1,2,1,2])
teamFy = np.array([10,9,10,11,10])
teamFz = np.array([8,8,8,8,8])
teamFt = np.array([4,5,4,4,5])

teamUx = np.array([10,10,11,11,12])
teamUy = np.array([7,6,6,6,5])
teamUz = np.array([4,4,4,3,3])
teamUt = np.array([4,4,5,4,4])

teamRx = np.array([1,1,1,1,1])
teamRy = np.array([8,8,9,9,9])
teamRz = np.array([6,7,6,6,6])
teamRt = np.array([5,4,4,4,4])

## CLASS F

In [106]:
meanFX = np.mean(teamFx)
meanFY = np.mean(teamFy)
meanFZ = np.mean(teamFz)
meanFT = np.mean(teamFt)

In [107]:
meanF = np.array([[meanFX],[meanFY],[meanFZ],[meanFT]])
meanF

array([[ 1.4],
       [10. ],
       [ 8. ],
       [ 4.4]])

In [101]:
F = np.array([teamFx,teamFy,teamFz,teamFt])
F

array([[ 1,  1,  2,  1,  2],
       [10,  9, 10, 11, 10],
       [ 8,  8,  8,  8,  8],
       [ 4,  5,  4,  4,  5]])

In [102]:
covF = np.cov(F)
covF

array([[ 0.3 ,  0.  ,  0.  ,  0.05],
       [ 0.  ,  0.5 ,  0.  , -0.25],
       [ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.05, -0.25,  0.  ,  0.3 ]])

In [103]:
for i in range(len(covF)):
    for j in range(len(covF)):
        if covF[i][i] == 0:
            covF[i][i] = 1

In [104]:
covF

array([[ 0.3 ,  0.  ,  0.  ,  0.05],
       [ 0.  ,  0.5 ,  0.  , -0.25],
       [ 0.  ,  0.  ,  1.  ,  0.  ],
       [ 0.05, -0.25,  0.  ,  0.3 ]])

In [61]:
newx,newy,newz,newt = 1,10,8,4
pi = 6.28**2   #2 = n/2  n=sınıf sayısı,probleme göre değiştir n=4
s1 = ((linalg.det(covF))**0.5)*pi
newM = np.array([[newx-meanFX],[newy-meanFY],[newz-meanFZ],[newt-meanFT]])
tM = np.transpose(newM)
v1= np.linalg.inv(covF)
c1 = np.dot(tM,v1)
c2 = np.dot(c1,newM)
c3 = -0.5 * c2[0][0]
s2 = np.exp(c3)
sonucF =  (1/s1) * s2 
sonucF

0.0880104049079373

## Class U

In [108]:
meanUX = np.mean(teamUx)
meanUX

10.8

In [109]:
meanUY = np.mean(teamUy)
meanUY

6.0

In [110]:
meanUZ = np.mean(teamUz)
meanUZ

3.6

In [111]:
meanUT = np.mean(teamUt)
meanUT

4.2

In [112]:
meanU = np.array([[meanUX],[meanUY],[meanUZ],[meanUT]])
meanU

array([[10.8],
       [ 6. ],
       [ 3.6],
       [ 4.2]])

In [113]:
U= np.array([teamUx,teamUy,teamUz,teamUt])

In [114]:
covU = np.cov(U)
covU

array([[ 0.7 , -0.5 , -0.35,  0.05],
       [-0.5 ,  0.5 ,  0.25,  0.  ],
       [-0.35,  0.25,  0.3 ,  0.1 ],
       [ 0.05,  0.  ,  0.1 ,  0.2 ]])

In [115]:
newx,newy,newz,newt = 1,10,8,4
pi = 6.28**2   #1 = n/2  n=sınıf sayısı,probleme göre değiştir
s1 = ((linalg.det(covU))**0.5)*pi
newM = np.array([[newx-meanUX],[newy-meanUY],[newz-meanUZ],[newt-meanUT]])
tM = np.transpose(newM)
v1= np.linalg.inv(covU)
c1 = np.dot(tM,v1)
c2 = np.dot(c1,newM)
c3 = -0.5 * c2[0][0]
s2 = np.exp(c3)
sonucB =  (1/s1) * s2 
sonucB

2.5721646796130074e-55

## Class R

In [121]:
meanRX = np.mean(teamRx)
meanRX

1.0

In [122]:
meanRY = np.mean(teamRy)
meanRY

8.6

In [123]:
meanRZ = np.mean(teamRz)
meanRZ

6.2

In [124]:
meanRT = np.mean(teamTt)
meanRT

5.0

In [125]:
meanR = np.array([[meanRX],[meanRY],[meanRZ],[meanRT]])
meanR

array([[1. ],
       [8.6],
       [6.2],
       [5. ]])

In [126]:
R = np.array([teamRx,teamRy,teamRz,teamRt])
R

array([[1, 1, 1, 1, 1],
       [8, 8, 9, 9, 9],
       [6, 7, 6, 6, 6],
       [5, 4, 4, 4, 4]])

In [127]:
covR = np.cov(R)
covR

array([[ 0.  ,  0.  ,  0.  ,  0.  ],
       [ 0.  ,  0.3 , -0.15, -0.15],
       [ 0.  , -0.15,  0.2 , -0.05],
       [ 0.  , -0.15, -0.05,  0.2 ]])

In [77]:
for i in range(len(covR)):
    for j in range(len(covR)):
        if covR[i][i] == 0:
            covR[i][i] = 1

In [78]:
newx,newy,newz,newt = 1,10,8,4
pi = 6.28**2   #2 = n/2  n=sınıf sayısı,probleme göre değiştir n=4
s1 = ((linalg.det(covR))**0.5)*pi
newM = np.array([[newx-meanRX],[newy-meanRY],[newz-meanRZ],[newt-meanRT]])
tM = np.transpose(newM)
v1= np.linalg.inv(covR)
c1 = np.dot(tM,v1)
c2 = np.dot(c1,newM)
c3 = -0.5 * c2[0][0]
s2 = np.exp(c3)
sonucF =  (1/s1) * s2 
sonucF

0.0

## Class K

In [79]:
meanKX = np.mean(teamKx)
meanKY = np.mean(teamKy)
meanKZ = np.mean(teamKz)
meanKT = np.mean(teamKt)

In [80]:
meanK = np.array([[meanKX],[meanKY],[meanKZ],[meanKT]])
meanK

array([[5.2],
       [8.4],
       [6.4],
       [4. ]])

In [81]:
K = np.array([teamKx,teamKy,teamKz,teamKt])
K

array([[5, 5, 5, 6, 5],
       [8, 9, 9, 8, 8],
       [7, 6, 6, 6, 7],
       [4, 4, 4, 4, 4]])

In [82]:
covK = np.cov(K)
covK

array([[ 0.2, -0.1, -0.1,  0. ],
       [-0.1,  0.3, -0.2,  0. ],
       [-0.1, -0.2,  0.3,  0. ],
       [ 0. ,  0. ,  0. ,  0. ]])

In [83]:
for i in range(len(covK)):
    for j in range(len(covK)):
        if covK[i][i] == 0:
            covK[i][i] = 1

In [84]:
newx,newy,newz,newt = 1,10,8,4
pi = 6.28**2   #2 = n/2  n=sınıf sayısı,probleme göre değiştir n=4
s1 = ((linalg.det(covK))**0.5)*pi
newM = np.array([[newx-meanKX],[newy-meanKY],[newz-meanKZ],[newt-meanKT]])
tM = np.transpose(newM)
v1= np.linalg.inv(covK)
c1 = np.dot(tM,v1)
c2 = np.dot(c1,newM)
c3 = -0.5 * c2[0][0]
s2 = np.exp(c3)
sonucK =  (1/s1) * s2 
sonucK

0.0

## Class 9

In [85]:
meanDX = np.mean(teamDx)
meanDY = np.mean(teamDy)
meanDZ = np.mean(teamDz)
meanDT = np.mean(teamDt)

In [86]:
meanD = np.array([[meanDX],[meanDY],[meanDZ],[meanDT]])
meanD

array([[2. ],
       [5.6],
       [2. ],
       [9. ]])

In [87]:
D = np.array([teamDx,teamDy,teamDz,teamDt])
D

array([[1, 2, 2, 3, 2],
       [5, 5, 6, 6, 6],
       [2, 2, 2, 2, 2],
       [9, 9, 9, 9, 9]])

In [88]:
covD = np.cov(D)
covD

array([[0.5 , 0.25, 0.  , 0.  ],
       [0.25, 0.3 , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  ]])

In [89]:
for i in range(len(covD)):
    for j in range(len(covD)):
        if covD[i][i] == 0:
            covD[i][i] = 1

In [90]:
newx,newy,newz,newt = 1,10,8,4
pi = 6.28**2   #2 = n/2  n=sınıf sayısı,probleme göre değiştir n=4
s1 = ((linalg.det(covD))**0.5)*pi
newM = np.array([[newx-meanDX],[newy-meanDY],[newz-meanDZ],[newt-meanDT]])
tM = np.transpose(newM)
v1= np.linalg.inv(covD)
c1 = np.dot(tM,v1)
c2 = np.dot(c1,newM)
c3 = -0.5 * c2[0][0]
s2 = np.exp(c3)
sonucD =  (1/s1) * s2 
sonucD

2.885353626372774e-45

## Class 4

In [91]:
meanTX = np.mean(teamTx)
meanTY = np.mean(teamTy)
meanTZ = np.mean(teamTz)
meanTT = np.mean(teamTt)

In [92]:
meanT = np.array([[meanTX],[meanTY],[meanTZ],[meanTT]])
meanT

array([[ 2. ],
       [10. ],
       [ 2.8],
       [ 5. ]])

In [93]:
T = np.array([teamTx,teamTy,teamTz,teamTt])
T

array([[ 1,  2,  2,  3,  2],
       [10, 10, 10, 10, 10],
       [ 3,  2,  3,  3,  3],
       [ 5,  5,  5,  5,  5]])

In [94]:
covT = np.cov(T)
covT

array([[0.5, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. ],
       [0. , 0. , 0.2, 0. ],
       [0. , 0. , 0. , 0. ]])

In [95]:
for i in range(len(covT)):
    for j in range(len(covT)):
        if covT[i][i] == 0:
            covT[i][i] = 1

In [96]:
newx,newy,newz,newt = 1,10,8,4
pi = 6.28**2   #2 = n/2  n=sınıf sayısı,probleme göre değiştir n=4
s1 = ((linalg.det(covT))**0.5)*pi
newM = np.array([[newx-meanTX],[newy-meanTY],[newz-meanTZ],[newt-meanTT]])
tM = np.transpose(newM)
v1= np.linalg.inv(covT)
c1 = np.dot(tM,v1)
c2 = np.dot(c1,newM)
c3 = -0.5 * c2[0][0]
s2 = np.exp(c3)
sonucD =  (1/s1) * s2 
sonucD

7.840287944841769e-32